guard 'livereload', :grace_period => 1 do
    # watch(%r{app/views/.+\.(erb|haml|slim)$})
    watch(%r{frontend/.+\.(css|js|html)})
    # watch(%r{module/BirdsiFrontend/assets/stylesheets/.+\.(scss|css|js|html|phtml)})

    # watch(%r{(frontend|backend)(/assets/\w+/(.+\.(css|js|html))).*}) { |m| "/assets/#{m[3]}" }
end

guard :compass, configuration_file: 'config.rb', compile_on_start: true do
    watch(%r{frontend/assets/sass/.+\.sass})
end
